apiVersion: v1
description: EFK(Elasticsearch + Filebeat + Kibana)
name: efk
version: 6.8.18
appVersion: 6.8.18
icon: file://../efk-logo.jpg
sources:
- https://www.elastic.co/products/elasticsearch
- https://www.elastic.co/products/kibana
- https://fluentbit.io/
home: https://www.elastic.co
maintainers:
- name: guangbochen
  email: support@rancher.com
engine: gotpl
