# Default values for efk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
elasticsearch:
  enabled: true
  image: "library/elasticsearch"
  imageTag: "6.8.18"
  enableProxy: true


kibana:
  enabled: true
  image: "library/kibana"
  imageTag: "6.8.18"

filebeat:
  enabled: true
  image: "library/filebeat"
  imageTag: "6.8.18"

metricbeat:
  enabled: true
  image: "library/metricbeat"
  imageTag: "6.8.18"
  kube-state-metrics:
    image:
      repository: ranchercharts/coreos-kube-state-metrics
      tag: v1.7.2

global:
  nginxProxy:
    repository: rancher/nginx
    tag: 1.15.8-alpine
